### ISSUE TITLE
Generating input for train RF model 

### ISSUE THREAD

**Issue by jgunti-code** [parklab/MosaicForecast#11]
Hi, I am having trouble with generating the input file when I want to create my own training set. This is what you guys said:

The input file should be a list of pre-generated read-level features, adding a column termed "phase" (Phase model) or "phase_model_corrected" (Refined genotypes model).

I can use the ReadLevel_feature_extraction.py to create the read-level features but unsure how to add the phasing the all.phasing file does not have the same number of variants as the read-level so unsure how to get the phasing. Any help would be great! Thank you.

**Comment by douym** [comment]
> Hi, I am having trouble with generating the input file when I want to create my own training set. This is what you guys said:
> 
> The input file should be a list of pre-generated read-level features, adding a column termed "phase" (Phase model) or "phase_model_corrected" (Refined genotypes model).
> 
> I can use the ReadLevel_feature_extraction.py to create the read-level features but unsure how to add the phasing the all.phasing file does not have the same number of variants as the read-level so unsure how to get the phasing. Any help would be great! Thank you.

Hi @jgunti-code !

Sorry for the late reply. You could use the built-in command "join" in linux to join the read-level feature file and the all.phasing file.

Best wishes,

Yanmei

**Comment by jgunti-code** [comment]
Thank you!
