### ISSUE TITLE
Refined Models for Indels

### ISSUE THREAD

**Issue by Rob-Schuetz** [parklab/MosaicForecast#12]
Hello,

Do you have trained indel models available that return refined genotype predictions?  When I pass model_type="Refine" and model_trained="insertions_250x.RF.rds" to Prediction.r, only Phase prediction is returned rather than refined genotype prediction.

Figure 3c-d in your paper (https://www.nature.com/articles/s41587-019-0368-8) shows refined genotype results for indels, and I'm curious as to which trained models were used to obtain these results.

Thanks,
Rob

**Comment by douym** [comment]
> Hello,
> 
> Do you have trained indel models available that return refined genotype predictions? When I pass model_type="Refine" and model_trained="insertions_250x.RF.rds" to Prediction.r, only Phase prediction is returned rather than refined genotype prediction.
> 
> Figure 3c-d in your paper (https://www.nature.com/articles/s41587-019-0368-8) shows refined genotype results for indels, and I'm curious as to which trained models were used to obtain these results.
> 
> Thanks,
> Rob

Hi Rob,

Thanks for your interest in using MosaicForecast! Unfortunately I have not trained Refine model for indels, since there are too few experimentally-evaluated phasable indels in our dataset to correct that.

Best wishes,

Yanmei

**Comment by Rob-Schuetz** [comment]
Hi Yanmei,

I see, thank you for getting back to me.  The phasing model should work just fine, I was just interested.

Thanks,
Rob
