### ISSUE TITLE
regions to filter out

### ISSUE THREAD

**Issue by sabrinacamp2** [parklab/MosaicForecast#14]
Hi,

I had a clarifying question. When you mention in the tutorial to `remove regions` that would impact mosaic variant calling, do you mean filter regions from the reference or from my own BAM?  

Also, do you have any suggestions on how to filter the BAM based off of these resources you listed? 

All the best,
Sabrina

**Comment by douym** [comment]
> Hi,
> 
> I had a clarifying question. When you mention in the tutorial to `remove regions` that would impact mosaic variant calling, do you mean filter regions from the reference or from my own BAM?
> 
> Also, do you have any suggestions on how to filter the BAM based off of these resources you listed?
> 
> All the best,
> Sabrina

Hi @sabrinacamp2 ,

Sorry for the confusing. I mean filter regions from the reference. Basically you could do this using bedtools, as described in the Snakefile (rule repeat_filter):
https://github.com/parklab/MosaicForecast/blob/master/Snakemake/Snakefile

I'd like to mention that we filtered more regions when detecting indels compared with SNVs, for example, if you want to detect SNVs, you could filter using this bed file: https://github.com/parklab/MosaicForecast/blob/master/resources/SegDup_and_clustered.GRCh37.bed; 
when you want to detect INDELs, you could filter using this bed file:
https://github.com/parklab/MosaicForecast/blob/master/resources/allrepeats_forindel.GRCh37.bed

Best wishes,

Yanmei

SegDup_and_clustered.GRCh37.bed
