### ISSUE TITLE
Phase.py

### ISSUE THREAD

**Issue by gevro** [parklab/MosaicForecast#15]
Hi! Thanks for a great tool. I'm starting to run MF, but I wasn't sure what the purpose of Phase.py is exactly.

In the snakemake pipeline (https://github.com/parklab/MosaicForecast/blob/master/Snakemake/Snakefile) the output of Phase.py goes into an output directory. But the outputs of Phase.py are never used as input for any other step.

Is it necessary to run Phase.py? What is the output used for?

**Comment by douym** [comment]
> Hi! Thanks for a great tool. I'm starting to run MF, but I wasn't sure what the purpose of Phase.py is exactly.
> 
> In the snakemake pipeline (https://github.com/parklab/MosaicForecast/blob/master/Snakemake/Snakefile) the output of Phase.py goes into an output directory. But the outputs of Phase.py are never used as input for any other step.
> 
> Is it necessary to run Phase.py? What is the output used for?

Hi @gevro , 

Thanks for your interest in MF!

When you need to re-train a new model or want to have a look at the local haplotype phasing of some candidate site of interset, you could use that Phase.py to generate phasing results.

If your data is WGS data, you probably do not need to run Phase to re-train the model, just apply our trained prediction model is ok.

Hope this answers your question!

Best wishes,

Yanmei

**Comment by gevro** [comment]
Thanks!
