### ISSUE TITLE
/etc/localtime warning

### ISSUE THREAD

**Issue by gevro** [parklab/MosaicForecast#17]
Hi, I'm getting this warning when running Prediction.R:
```
Warning message:
In normalizePath("/etc/localtime") :
  path[1]="/etc/localtime": No such file or directory
```

**Comment by douym** [comment]
> Hi, I'm getting this warning when running Prediction.R:
> 
> ```
> Warning message:
> In normalizePath("/etc/localtime") :
>   path[1]="/etc/localtime": No such file or directory
> ```

Hi @gevro , are you able to generate the final prediction results? I saw your new question posted

**Comment by gevro** [comment]
Yes, the .predictions file is still being generated, even though I am getting this error. Is this error something I should worry about?

**Comment by douym** [comment]
> Yes, the .predictions file is still being generated, even though I am getting this error. Is this error something I should worry about?

Hi @gevro ,

This might be correlated with docker versions...
https://github.com/docker/for-mac/issues/2396
I think it's not a concern as long as you could get the predictions~

Best,
Yanmei

**Comment by gevro** [comment]
Ok thanks.
