### ISSUE TITLE
Recommended filters from Mutect2 Filtermutectcalls

### ISSUE THREAD

**Issue by gevro** [parklab/MosaicForecast#19]
Hi,
In your current snakemake pipeline, the FILTER columns to remove from Mutect output (for example 'str_contraction' and 'multiallelic') are based on prior versions of Mutect. What FILTER values do you recommend to remove before input into MF from Mutect2 FilterMutectCalls?

base_qual
clustered_events
contamination
fragment
germline
haplotype
map_qual
multiallelic
orientation
panel_of_normals
position
slippage
strand_bias
weak_evidence

Thanks.

**Comment by douym** [comment]
> Hi,
> In your current snakemake pipeline, the FILTER columns to remove from Mutect output (for example 'str_contraction' and 'multiallelic') are based on prior versions of Mutect. What FILTER values do you recommend to remove before input into MF from Mutect2 FilterMutectCalls?
> 
> base_qual
> clustered_events
> contamination
> fragment
> germline
> haplotype
> map_qual
> multiallelic
> orientation
> panel_of_normals
> position
> slippage
> strand_bias
> weak_evidence
> 
> Thanks.

Hi @gevro ,

You could use multiallelic as the filter. The set of filters might not be so essential, since I've tried other callers (GATK, Strelka, MosaicHunter) with their default settings and still the precisions were high. 

Best wishes,

Yanmei

**Comment by gevro** [comment]
Thank you.
