### ISSUE TITLE
Recommended filters for Mutect2

### ISSUE THREAD

**Issue by gevro** [parklab/MosaicForecast#20]
Hi,
In reference to issue #19, I tried with > 10 different combinations of filters for Mutect2 output, but MosaicForecast is always giving > 500 variants from normal samples. I suspect there is an issue for MosaicForecast with Mutect2. Only when I use PASS only variants does MosaicForecast start to give reasonable results, but that defeats the purpose of using MosaicForecast.

Do you have experience running MosaicForecast with Mutect2, and if yes, what filters do you recommend to apply from these?
base_qual
clustered_events
contamination
fragment
germline
haplotype
map_qual
multiallelic
orientation
panel_of_normals
position
slippage
strand_bias
weak_evidence

Thanks!

**Comment by douym** [comment]
> Hi,
> In reference to issue #19, I tried with > 10 different combinations of filters for Mutect2 output, but MosaicForecast is always giving > 500 variants from normal samples. I suspect there is an issue for MosaicForecast with Mutect2. Only when I use PASS only variants does MosaicForecast start to give reasonable results, but that defeats the purpose of using MosaicForecast.
> 
> Do you have experience running MosaicForecast with Mutect2, and if yes, what filters do you recommend to apply from these?
> base_qual
> clustered_events
> contamination
> fragment
> germline
> haplotype
> map_qual
> multiallelic
> orientation
> panel_of_normals
> position
> slippage
> strand_bias
> weak_evidence
> 
> Thanks!

Hi @gevro ,

In our previous discussions I thought you have mentioned that filtering out strand-bias variants according to the sb_p column of MF could remove most of FPs?

Best,

Yanmei

**Comment by gevro** [comment]
1) What maximum (or minimum?) sb_p value do you recommend I filter with?
You can see again the sb_p values I got in issue #18.

2) But also, I'm not sure why MF is not already filtering these strand bias variants as part of its model?

Thanks!

**Comment by douym** [comment]
> 1. What maximum (or minimum?) sb_p value do you recommend I filter with?
>    You can see again the sb_p values I got in issue #18.
> 2. But also, I'm not sure why MF is not already filtering these strand bias variants as part of its model?
> 
> Thanks!

Hi @gevro ,

As we have discussed about this in the old thread, MF is not using hard filters. If you see that your data has a bias to enrich for false positive sites with such kind of issues, you could choose to add that hard filter. sb_p is a p-value, typically I would suggest to use p<0.05 to filter sites, you could also try other more relaxed criteria (p<0.01, for example).

Best,

Yanmei

**Comment by gevro** [comment]
Ok thanks!
