### ISSUE TITLE
MF on exomes

### ISSUE THREAD

**Issue by gevro** [parklab/MosaicForecast#23]
Hi, Is it possible to use MF on exomes? I'm guessing it would require a new model?

**Comment by douym** [comment]
> Hi, Is it possible to use MF on exomes? I'm guessing it would require a new model?

Hi @gevro ,

I have tried the model on some exome data before, and the results were resonable. It runs very quickly on exome data, and I think you could give it a try. There could be more false positive sites compared with WGS data, given the allelic imbalance generated by the capture procedure. Moreover, you may need to check the G>T vs. C>A mutations, given that oxidative damage (8-oxoG) is pretty frequent during the exome capture procedure.

Thanks,

Yanmei

**Comment by gevro** [comment]
Thank you!
