### ISSUE TITLE
installation stuck at solving environment

### ISSUE THREAD

**Issue by mmlian05** [parklab/MosaicForecast#24]
Hi, i'm encountering issue installing mosaicforecast. The following was what i've conducted but it seems conda is stuck at solving environment. Wondering how may i troubleshoot this issue? 

`conda env create -n MF --file environment.yaml`

```
Collecting package metadata (repodata.json): done
Solving environment: -
```

Thank you very much for the kind help.

**Comment by douym** [comment]
> Hi, i'm encountering issue installing mosaicforecast. The following was what i've conducted but it seems conda is stuck at solving environment. Wondering how may i troubleshoot this issue?
> 
> `conda env create -n MF --file environment.yaml`
> 
> ```
> Collecting package metadata (repodata.json): done
> Solving environment: -
> ```
> 
> Thank you very much for the kind help.

Sorry for the delayed response. Have you tried installing each package using conda separately?
