### ISSUE TITLE
Regions enriched for SNVs with >=3 haplotypes file download.

### ISSUE THREAD

**Issue by dongjuleem** [parklab/MosaicForecast#33]
Thank you for providing a great tool. I am trying to download the 'Regions enriched for SNVs with >=3 haplotypes' from the 'region to filter out' section on GitHub. I would appreciate it if you could confirm this for me.

**Comment by dongjuleem** [comment]
I also have a question about the demo version's results mentioned on the GitHub site, so I wanted to ask. 
In the results of 'Extraction of read-level features,' why is there an ID 'test~11~40316580~C~T' that is not present in the phasing results? I appreciate your time and assistance.

**Comment by douym** [comment]
> Thank you for providing a great tool. I am trying to download the 'Regions enriched for SNVs with >=3 haplotypes' from the 'region to filter out' section on GitHub. I would appreciate it if you could confirm this for me.

Hi @dongjuleem ,

Sorry for the delayed response. You could use the files here: https://github.com/parklab/MosaicForecast/tree/master/resources, the "clustered regions" indicate SNVs with >=3 haplotypes.
