### ISSUE TITLE
Combine the normal calls from mulusing CreateSomaticPanelOfNormals

### ISSUE THREAD

**Issue by dongjuleem** [parklab/MosaicForecast#34]
How do I generate the normals_for_pon_vcf.args when I proceed with Combine the normal calls from creating Create Somatic PanelOfNormals? Is it right to use the -V option instead of the -vcfs option after creation?

**Comment by douym** [comment]
Hi @dongjuleem ,

I have detailed description of how to generate ".args" in the snakemake pipeline:
https://github.com/parklab/MosaicForecast/blob/master/Snakemake/Snakefile

Hope that helps,

Y.

**Comment by dongjuleem** [comment]
@douym 
Thank you for the helpful explanation:)
