### ISSUE TITLE
use of bam files located in the Snakemake/bam_links_PON path

### ISSUE THREAD

**Issue by dongjuleem** [parklab/MosaicForecast#36]
Thank you for providing this great tool. While using it, I would like to use the bam files located in the Snakemake/bam_links_PON/ path. However, they are all symbolic links, and upon checking, I received a message saying that the page could not be found. Thank you for your time.

**Comment by douym** [comment]
> Thank you for providing this great tool. While using it, I would like to use the bam files located in the Snakemake/bam_links_PON/ path. However, they are all symbolic links, and upon checking, I received a message saying that the page could not be found. Thank you for your time.

Hi @dongjuleem , the panel of normals I used were generated using our own data. You could download and use the panel of normals generated by 1000 genomes project instead.

Best wishes,
Y.
