### ISSUE TITLE
37th line of args_generator.py

### ISSUE THREAD

**Issue by dongjuleem** [parklab/MosaicForecast#37]
Thank you for providing this grate tool. 
I encountered an issue while using the **args_generator.py** file. 
As far as I understand, the problem seems to occur when loading **X.intervals.list** and **Y.intervals.list** within the intervals folder. 

In the 37th line of args_generator.py
instead of `pattern=re.compile(r'([0-9]+)\.intervals\.list')`
I'd like to ask if it's okay to change to `pattern = re.compile(r'([0-9XY]+)\.intervals\.list')` and use it.

**Comment by douym** [comment]
> Thank you for providing this grate tool. I encountered an issue while using the **args_generator.py** file. As far as I understand, the problem seems to occur when loading **X.intervals.list** and **Y.intervals.list** within the intervals folder.
> 
> In the 37th line of args_generator.py instead of `pattern=re.compile(r'([0-9]+)\.intervals\.list')` I'd like to ask if it's okay to change to `pattern = re.compile(r'([0-9XY]+)\.intervals\.list')` and use it.

Hi @dongjuleem ,

Thanks for your message. It should be ok to run the prediction model on haploid chromosomes, but the haplotype phasing by "Phase.py" would be different compared with diploid chromosomes.

Best,
Y.

**Comment by dongjuleem** [comment]
Hi,
Sorry for the basic question.
I would like to apply the model to diploid chromosomes. 
In that case, is it advisable to apply it only to chromosomes 1 through 22, excluding X and Y from the intervals list?

**Comment by douym** [comment]
> Hi, Sorry for the basic question. I would like to apply the model to diploid chromosomes. In that case, is it advisable to apply it only to chromosomes 1 through 22, excluding X and Y from the intervals list?

Hi @dongjuleem ,

In that case, maybe you could exclude X and Y from Males and exclude Y from females.

Best wishes,

Y.

**Comment by dongjuleem** [comment]
i appreciate your time.
