### ISSUE TITLE
Snakefile workflow

### ISSUE THREAD

**Issue by dongjuleem** [parklab/MosaicForecast#38]
Thank you for providing this excellent tool. 
I have a question regarding the difference between the usage provided in the **README.md** and the **Snakefile workflow**.
Specifically, the Snakefile workflow does not include a step for **phasing using phase.py**. (Exclude the last step for re-training.)
Can you please provide some clarification on this difference?

**Comment by douym** [comment]
> Thank you for providing this excellent tool. I have a question regarding the difference between the usage provided in the **README.md** and the **Snakefile workflow**. Specifically, the Snakefile workflow does not include a step for **phasing using phase.py**. (Exclude the last step for re-training.) Can you please provide some clarification on this difference?

Hi @dongjuleem ,

Thanks for pointing that out. The snakemake workflow was designed for users who want to apply our pre-trained prediction model directly, while "phase.py" was for advanced users who what to train their customized models.

Best,
Y.
