### ISSUE TITLE
wigToBigWig does not work

### ISSUE THREAD

**Issue by wangxuedong930227** [parklab/MosaicForecast#4]
I created an environment using conda, but when i get the Mappability score through this command: wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw, some problems occurred :wigToBigWig: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by wigToBigWig)
wigToBigWig: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by wigToBigWig)
wigToBigWig: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by wigToBigWig)

**Comment by ponomarevsy** [comment]
And I am getting this error:

» ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw
zsh: bus error (core dumped)  ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw

There should be plenty of disk space, so, I assume, it is something else... Any insight into this? Thank you.

**Comment by douym** [comment]
> And I am getting this error:
> 
> » ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw
> zsh: bus error (core dumped) ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw
> 
> There should be plenty of disk space, so, I assume, it is something else... Any insight into this? Thank you.

Hi Ponomarrevsy,

I think the bus error is due to lack of enough memory. This process is pretty memory-consuming. Could you try to require more memory (at least 30G)? 

If your computer does not have that much memory, it's ok, because I have a file ready to use in the docker image (k24.umap.wg.bw), and you could either use it in the docker or download it to your computer. 

Please tell me if you have further questions! Thanks a lot!

**Comment by douym** [comment]
> I created an environment using conda, but when i get the Mappability score through this command: wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw, some problems occurred :wigToBigWig: /lib64/libz.so.1: version `ZLIB_1.2.3.3' not found (required by wigToBigWig) wigToBigWig: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by wigToBigWig)
> wigToBigWig: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by wigToBigWig)

Hi xuedong,

So sorry that I missed your question! Could you tried the following link to solve your problem and tell me if it works:
https://stackoverflow.com/questions/19471683/lib-libc-so-6-version-glibc-2-17-not-found

Moreover, I have a "k24.umap.wg.bw"  file ready in the docker image, you could also download it to your local computer if you still fail the generate the file.

Please tell me if you have further questions!

**Comment by ponomarevsy** [comment]
Thanks for your help, @douym! Asking for 32G of RAM solved the "bus error" issue:

» ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw

» ls                                    
hg19.chrom.sizes  k100.umap.wg.gz  k24.umap.wg.bw  k36.umap.bed.gz  k50.umap.bed.gz
k100.umap.bed.gz  k24.umap.bed.gz  k24.umap.wg.gz  k36.umap.wg.gz   k50.umap.wg.gz 

Best regards.

**Comment by douym** [comment]
> Thanks for your help, @douym! Asking for 32G of RAM solved the "bus error" issue:
> 
> » ../wigToBigWig <(zcat k24.umap.wg.gz) hg19.chrom.sizes k24.umap.wg.bw
> 
> » ls
> hg19.chrom.sizes k100.umap.wg.gz k24.umap.wg.bw k36.umap.bed.gz k50.umap.bed.gz
> k100.umap.bed.gz k24.umap.bed.gz k24.umap.wg.gz k36.umap.wg.gz k50.umap.wg.gz
> 
> Best regards.

Thanks a lot for your feedback!
