### ISSUE TITLE
predictedhap3ormore_cluster.GRCh38.bed not in place

### ISSUE THREAD

**Issue by dragonf97** [parklab/MosaicForecast#40]
Hi,

I'm trying mosaicforecast on my dataset, and while i was setting the basics I found out that something is missing.

Regions enriched for SNVs with >=3 haplotypes (should be removed before calling all kinds of mosaics):

wget https://raw.githubusercontent.com/parklab/MosaicForecast/master/resources/predictedhap3ormore_cluster.GRCh38.bed

The part here is missing. Is there any way i can get that file? or those that file no longer useful?

Thanks,
Matt

**Comment by douym** [comment]
Hi @dragonf97 ,
Sorry for the confusion. The updated file is here, I merged the hap3 file("clustered") with Segmental Duplicated regions:
https://github.com/parklab/MosaicForecast/blob/master/resources/SegDup_and_clustered.GRCh38.bed
Hope that helps!

Best wishes,

Yanmei

**Comment by dragonf97** [comment]
Thanks for your assist!!
