### ISSUE TITLE
Phase.py

### ISSUE THREAD

**Issue by jgunti-code** [parklab/MosaicForecast#5]
I am having a problem running Phase.py I am using the docker image so I don't understand the error:

singularity exec -B /projects/b1073/ mosaicforecast_0.0.1.sif python /projects/b1073/pipelines/genomes/MosaicForecast/Phase.py /projects/b1073/pipelines/genomes/MosaicForecast/demo /projects/b1073/pipelines/genomes/MosaicForecast/demo/phasing /projects/b1073/pipelines/genomes/resources/MF_38_Resources/GRCh38_full_analysis_set_plus_decoy_hla.fa /projects/b1073/pipelines/genomes/MosaicForecast/demo/test.input 20 /projects/b1073/pipelines/genomes/resources/MF_38_Resources/hg38/k24.umap.wg.bw 2 bam
Traceback (most recent call last):
  File "/projects/b1073/pipelines/genomes/MosaicForecast/Phase.py", line 26, in <module>
    import pysam
  File "/home/jrg4257/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by douym** [comment]
> I am having a problem running Phase.py I am using the docker image so I don't understand the error:
> 
> singularity exec -B /projects/b1073/ mosaicforecast_0.0.1.sif python /projects/b1073/pipelines/genomes/MosaicForecast/Phase.py /projects/b1073/pipelines/genomes/MosaicForecast/demo /projects/b1073/pipelines/genomes/MosaicForecast/demo/phasing /projects/b1073/pipelines/genomes/resources/MF_38_Resources/GRCh38_full_analysis_set_plus_decoy_hla.fa /projects/b1073/pipelines/genomes/MosaicForecast/demo/test.input 20 /projects/b1073/pipelines/genomes/resources/MF_38_Resources/hg38/k24.umap.wg.bw 2 bam
> Traceback (most recent call last):
> File "/projects/b1073/pipelines/genomes/MosaicForecast/Phase.py", line 26, in 
> import pysam
> File "/home/jrg4257/.local/lib/python3.6/site-packages/pysam/**init**.py", line 5, in 
> from pysam.libchtslib import *
> ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Hi @jgunti-code , sorry I just see your message. Did you manage to solve the problem? Thanks!

**Comment by jgunti-code** [comment]
I did thanks! 

Respectfully, 

               Jonathan Gunti
