### ISSUE TITLE
File predictedhap3ormore_cluster.GRCh38.bed not included

### ISSUE THREAD

**Issue by wdecoster** [parklab/MosaicForecast#6]
Hi,

I'm very much interested in trying this on my dataset, and want to use GRCh38. 
The README mentions:
`wget https://raw.githubusercontent.com/parklab/MosaicForecast/master/resources/predictedhap3ormore_cluster.GRCh38.bed`
However, that file does not exist... and it also seems other files in resources are just for GRCh37 :-(

Thanks,
Wouter

**Comment by douym** [comment]
> Hi,
> 
> I'm very much interested in trying this on my dataset, and want to use GRCh38.
> The README mentions:
> `wget https://raw.githubusercontent.com/parklab/MosaicForecast/master/resources/predictedhap3ormore_cluster.GRCh38.bed`
> However, that file does not exist... and it also seems other files in resources are just for GRCh37 :-(
> 
> Thanks,
> Wouter

@wdecoster thanks a lot for your interest in MosaicForecast!
Terribly sorry for this and thanks a lot for picking out this error, I've uploaded the file now. 

Thanks a lot, and best wishes,

Yanmei

**Comment by wdecoster** [comment]
Great, thanks! Do you also have a file like `resources/SegDup_and_clustered.bed` for GRCh38? Or how can I make one?

**Comment by douym** [comment]
> Great, thanks! Do you also have a file like `resources/SegDup_and_clustered.bed` for GRCh38? Or how can I make one?
@wdecoster sure! the file has been uploaded to the resources.
