### ISSUE TITLE
Errors during run

### ISSUE THREAD

**Issue by wdecoster** [parklab/MosaicForecast#7]
Phase.py hasn't finished yet, but already reported some errors. I am using a CRAM file as input.
I use the following command: python Phase.py crams/ phased GRCh38.fa PoN-filter/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.bed 20 hg38/k24.umap.wg.bw 4 cram

As an aside, the command-line interface is rather inconvenient, forcing me to remember the order of arguments, without any defaults or useful help information when I forget one argument. Please consider using [argparse](https://docs.python.org/3/library/argparse.html). It will make argument handling a lot easier for you, and for your users.

The errors printed to the terminal:

```
processing chromosomes........................
[W::hts_close] EOF marker is absent. The input is probably truncated
[W::hts_close] EOF marker is absent. The input is probably truncated
samtools index: "phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram" is in a format that cannot be usefully indexed



check the format of your input file:
chr	pos-1	pos	ref	alt	sample
check the format of your input file:
chr	pos-1	pos	ref	alt	sample
```

It seems to me that `phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram` is a file created by MosaicForecast. So it created a corrupted file? I checked the file and it is empty. MosaicForecast has already created 38503 files in tmp?!

The other comments are about the format of the input file. But for that I used the file generated by `MuTect2-PoN_filter.py`. It's also not a very informative error message if it doesn't tell me what's wrong.

**Comment by wdecoster** [comment]
While repeating the command I receive the same error for different locations:

```
samtools index: "phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr10_94989681.mosaic.minor.sorted.cram" is in a format that cannot be usefully indexed
[E::hts_hopen] Failed to open file phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr21_33025879.mosaic.minor.sorted.cram
[E::hts_open_format] Failed to open file phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr21_33025879.mosaic.minor.sorted.cram
samtools index: failed to open "phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr21_33025879.mosaic.minor.sorted.cram"
```

**Comment by douym** [comment]
> Phase.py hasn't finished yet, but already reported some errors. I am using a CRAM file as input.
> I use the following command: python Phase.py crams/ phased GRCh38.fa PoN-filter/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.bed 20 hg38/k24.umap.wg.bw 4 cram
> 
> As an aside, the command-line interface is rather inconvenient, forcing me to remember the order of arguments, without any defaults or useful help information when I forget one argument. Please consider using [argparse](https://docs.python.org/3/library/argparse.html). It will make argument handling a lot easier for you, and for your users.
> 
> The errors printed to the terminal:
> 
> ```
> processing chromosomes........................
> [W::hts_close] EOF marker is absent. The input is probably truncated
> [W::hts_close] EOF marker is absent. The input is probably truncated
> samtools index: "phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram" is in a format that cannot be usefully indexed
> 
> 
> 
> check the format of your input file:
> chr	pos-1	pos	ref	alt	sample
> check the format of your input file:
> chr	pos-1	pos	ref	alt	sample
> ```
> 
> It seems to me that `phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram` is a file created by MosaicForecast. So it created a corrupted file? I checked the file and it is empty. MosaicForecast has already created 38503 files in tmp?!
> 
> The other comments are about the format of the input file. But for that I used the file generated by `MuTect2-PoN_filter.py`. It's also not a very informative error message if it doesn't tell me what's wrong.

Hi @wdecoster ,

Thanks a lot for your question and great suggestion! I'll look into argparse later.

I noticed that the "EOF marker is absent, The input is probably truncated" for your cram file. Have you checked if your input cram file is truncated?

Best wishes,

Yanmei

**Comment by wdecoster** [comment]
Hi Yanmei,

I just confirmed that my cram file is perfectly fine with samtools quickcheck and samtools view. I think the error message comes from the cram files that MF creates in its /tmp/ folder.

I just looked in the code of Phase.py, and saw that the message `"check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample"` is behind a bare try-except block, meaning that if ANYTHING goes wrong you only tell the user to check their input file, without raising any more informative errors. That's not really recommended. If anything, I would suggest the following, and add [logging](https://docs.python.org/3.8/library/logging.html) in your script:


try:
   #do all your stuff here
except Exception as e:
   sys.stderr.write("something went wrong, please check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample")
   #print "e" to the log file
   raise

Elsewhere I noticed a `try:... except: continue ` block, meaning that you effectively silence all errors there. You know your code better than I do, but generally, that's not an appropriate way of handling errors.

Regards,
Wouter

**Comment by douym** [comment]
> Hi Yanmei,
> 
> I just confirmed that my cram file is perfectly fine with samtools quickcheck and samtools view. I think the error message comes from the cram files that MF creates in its /tmp/ folder.
> 
> I just looked in the code of Phase.py, and saw that the message `"check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample"` is behind a bare try-except block, meaning that if ANYTHING goes wrong you only tell the user to check their input file, without raising any more informative errors. That's not really recommended. If anything, I would suggest the following, and add [logging](https://docs.python.org/3.8/library/logging.html) in your script:
> 
> try:
> #do all your stuff here
> except Exception as e:
> sys.stderr.write("something went wrong, please check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample")
> #print "e" to the log file
> raise
> 
> Elsewhere I noticed a `try:... except: continue ` block, meaning that you effectively silence all errors there. You know your code better than I do, but generally, that's not an appropriate way of handling errors.
> 
> Regards,
> Wouter

Hi @wdecoster ,

I asked if the bam is ok because your error message "EOF marker is absent" seems to happen during the 1st stage of running bigWigAverageOverBed.

Do you mind sending me a piece of your bam file, so I could repeat your error and see what's going on?

Thanks,

Yanmei

**Comment by douym** [comment]
> Hi Yanmei,
> 
> I just confirmed that my cram file is perfectly fine with samtools quickcheck and samtools view. I think the error message comes from the cram files that MF creates in its /tmp/ folder.
> 
> I just looked in the code of Phase.py, and saw that the message `"check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample"` is behind a bare try-except block, meaning that if ANYTHING goes wrong you only tell the user to check their input file, without raising any more informative errors. That's not really recommended. If anything, I would suggest the following, and add [logging](https://docs.python.org/3.8/library/logging.html) in your script:
> 
> try:
> #do all your stuff here
> except Exception as e:
> sys.stderr.write("something went wrong, please check the format of your input file:\nchr\tpos-1\tpos\tref\talt\tsample")
> #print "e" to the log file
> raise
> 
> Elsewhere I noticed a `try:... except: continue ` block, meaning that you effectively silence all errors there. You know your code better than I do, but generally, that's not an appropriate way of handling errors.
> 
> Regards,
> Wouter

If you would kindly provide the piece of bam file, I would need the local region of your bam (from upstream 2000bp to downstream 2000bp) along with your input position that returns the error.

My email address is yanmei_dou@hms.harvard.edu if that's convenient to you.

**Comment by wdecoster** [comment]
Those datasets are confidential, I can't share those.

**Comment by douym** [comment]
> Those datasets are confidential, I can't share those.

Ok, then I would suggest you to run bigWigAverageOverBed first and see if there's any error message.

**Comment by wdecoster** [comment]
I can do that, what is the command I should use?

**Comment by douym** [comment]
> I can do that, what is the command I should use?

it's downloaded from ucsc:
wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bigWigAverageOverBed
usage:
   bigWigAverageOverBed in.bw in.bed out.tab

**Comment by wdecoster** [comment]
> usage:
> bigWigAverageOverBed in.bw in.bed out.tab

Not terribly helpful if you aren't telling me which be and which bed file to use, but okay I can also look into other software for mosaic variants. 

Cheers,
W

**Comment by douym** [comment]
> > usage:
> > bigWigAverageOverBed in.bw in.bed out.tab
> 
> Not terribly helpful if you aren't telling me which bw and which bed file to use, but okay I can also look into other software for mosaic variants.
> 
> Cheers,
> W

Sorry I cannot solve the problem for you. It would be most helpful if you could send me a test bam to replicate the error, but it's up to you.

**Comment by douym** [comment]
> Phase.py hasn't finished yet, but already reported some errors. I am using a CRAM file as input.
> I use the following command: python Phase.py crams/ phased GRCh38.fa PoN-filter/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.bed 20 hg38/k24.umap.wg.bw 4 cram
> 
> As an aside, the command-line interface is rather inconvenient, forcing me to remember the order of arguments, without any defaults or useful help information when I forget one argument. Please consider using [argparse](https://docs.python.org/3/library/argparse.html). It will make argument handling a lot easier for you, and for your users.
> 
> The errors printed to the terminal:
> 
> ```
> processing chromosomes........................
> [W::hts_close] EOF marker is absent. The input is probably truncated
> [W::hts_close] EOF marker is absent. The input is probably truncated
> samtools index: "phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram" is in a format that cannot be usefully indexed
> 
> 
> 
> check the format of your input file:
> chr	pos-1	pos	ref	alt	sample
> check the format of your input file:
> chr	pos-1	pos	ref	alt	sample
> ```
> 
> It seems to me that `phased/tmp/C_NA01-118_FCX_Exome.FCHLHNVDSXX_md.chr17_56923653.mosaic.minor.sorted.cram` is a file created by MosaicForecast. So it created a corrupted file? I checked the file and it is empty. MosaicForecast has already created 38503 files in tmp?!
> 
> The other comments are about the format of the input file. But for that I used the file generated by `MuTect2-PoN_filter.py`. It's also not a very informative error message if it doesn't tell me what's wrong.

One more comment which might be helpful:
Actually one most likely reason to generate an empty minor.bam file is there's in lack of alternative alleles at that position of your input bam file.
I used pysam to count alt alleles at each position. It would be helpful you could take a moment to check if there are any alt alleles at that position reporting error.
I have a code written to calculate the alt allele count as well as the VAFs here in case you want to use:
https://github.com/douym/tools/blob/master/VAF_calculate.py.

Best wishes,

Yanmei
