### ISSUE TITLE
MuTect2-PON.py - multiallelic values

### ISSUE THREAD

**Issue by vmscmams** [parklab/MosaicForecast#9]
Hello!,
Thanks for your reply, I've made the change you suggested and it still fails but using that logic I've changed to BAM and it worked.

Now I'm testing with my exome dataset and it fails since my mutect2 VCF has multi-allelic values and the MuTect2-PoN_filter.py script fails when it tries to convert that a value to Float.

Error Msg:
Traceback (most recent call last):
File "/usr/local/bin/MuTect2-PoN_filter.py", line 48, in
AF=float(INFOs[2])
ValueError: could not convert string to float: '0.429,0.286'

Data string on my VCF.
chr1 181583 . CGGGGGG C,CGG . clustered_events;germline;map_qual;multiallelic CONTQ=30;DP=4;ECNT=2;GERMQ=1;MBQ=0,30,30;MFRL=186,320,326;MMQ=27,60,60;MPOS=23,25;POPAF=7.30,7.30;RPA=17,11,13;RU=G;SEQQ=2;STR;STRANDQ=93;STRQ=93;TLOD=7.62,3.37 GT:AD:AF:DP:F1R2:F2R1:SB 0/1/2:1,2,1:0.429,0.286:4:0,1,0:0,1,1:1,0,3,0

Did you experience datasets with this kind of values?

PS: tried to run mutect2 with max allels parameter in 1 and still generates 2 values.

**Comment by douym** [comment]
> Hello!,
> Thanks for your reply, I've made the change you suggested and it still fails but using that logic I've changed to BAM and it worked.
> 
> Now I'm testing with my exome dataset and it fails since my mutect2 VCF has multi-allelic values and the MuTect2-PoN_filter.py script fails when it tries to convert that a value to Float.
> 
> Error Msg:
> Traceback (most recent call last):
> File "/usr/local/bin/MuTect2-PoN_filter.py", line 48, in
> AF=float(INFOs[2])
> ValueError: could not convert string to float: '0.429,0.286'
> 
> Data string on my VCF.
> chr1 181583 . CGGGGGG C,CGG . clustered_events;germline;map_qual;multiallelic CONTQ=30;DP=4;ECNT=2;GERMQ=1;MBQ=0,30,30;MFRL=186,320,326;MMQ=27,60,60;MPOS=23,25;POPAF=7.30,7.30;RPA=17,11,13;RU=G;SEQQ=2;STR;STRANDQ=93;STRQ=93;TLOD=7.62,3.37 GT:AD:AF:DP:F1R2:F2R1:SB 0/1/2:1,2,1:0.429,0.286:4:0,1,0:0,1,1:1,0,3,0
> 
> Did you experience datasets with this kind of values?
> 
> PS: tried to run mutect2 with max allels parameter in 1 and still generates 2 values.



> Hello!,
> Thanks for your reply, I've made the change you suggested and it still fails but using that logic I've changed to BAM and it worked.
> 
> Now I'm testing with my exome dataset and it fails since my mutect2 VCF has multi-allelic values and the MuTect2-PoN_filter.py script fails when it tries to convert that a value to Float.
> 
> Error Msg:
> Traceback (most recent call last):
> File "/usr/local/bin/MuTect2-PoN_filter.py", line 48, in
> AF=float(INFOs[2])
> ValueError: could not convert string to float: '0.429,0.286'
> 
> Data string on my VCF.
> chr1 181583 . CGGGGGG C,CGG . clustered_events;germline;map_qual;multiallelic CONTQ=30;DP=4;ECNT=2;GERMQ=1;MBQ=0,30,30;MFRL=186,320,326;MMQ=27,60,60;MPOS=23,25;POPAF=7.30,7.30;RPA=17,11,13;RU=G;SEQQ=2;STR;STRANDQ=93;STRQ=93;TLOD=7.62,3.37 GT:AD:AF:DP:F1R2:F2R1:SB 0/1/2:1,2,1:0.429,0.286:4:0,1,0:0,1,1:1,0,3,0
> 
> Did you experience datasets with this kind of values?
> 
> PS: tried to run mutect2 with max allels parameter in 1 and still generates 2 values.

Hi @vmscmams ,
Have you tri
https://github.com/parklab/MosaicForecast/tree/master/Snakemake

> Hello!,
> Thanks for your reply, I've made the change you suggested and it still fails but using that logic I've changed to BAM and it worked.
> 
> Now I'm testing with my exome dataset and it fails since my mutect2 VCF has multi-allelic values and the MuTect2-PoN_filter.py script fails when it tries to convert that a value to Float.
> 
> Error Msg:
> Traceback (most recent call last):
> File "/usr/local/bin/MuTect2-PoN_filter.py", line 48, in
> AF=float(INFOs[2])
> ValueError: could not convert string to float: '0.429,0.286'
> 
> Data string on my VCF.
> chr1 181583 . CGGGGGG C,CGG . clustered_events;germline;map_qual;multiallelic CONTQ=30;DP=4;ECNT=2;GERMQ=1;MBQ=0,30,30;MFRL=186,320,326;MMQ=27,60,60;MPOS=23,25;POPAF=7.30,7.30;RPA=17,11,13;RU=G;SEQQ=2;STR;STRANDQ=93;STRQ=93;TLOD=7.62,3.37 GT:AD:AF:DP:F1R2:F2R1:SB 0/1/2:1,2,1:0.429,0.286:4:0,1,0:0,1,1:1,0,3,0
> 
> Did you experience datasets with this kind of values?
> 
> PS: tried to run mutect2 with max allels parameter in 1 and still generates 2 values.

Hi @vmscmams ,

It's strange that cram doesn't work for you, since I've tested that command line and it works properly... May I know what is your error message if using "cram"?

I would suggest you to use the Snakemake pipeline here https://github.com/parklab/MosaicForecast/tree/master/Snakemake, it's more convenient and has been tested by multiple individuals. The 'multiallelic' sites were filtered in the Snakemake pipeline. Thanks for the reminding, I just realized that the multiallelic sites were not filtered in the MuTect2-PoN_filter.py script. I've added that filter in the script and pushed to the github.

Thanks,

Yanmei

**Comment by vmscmams** [comment]
Hello Yanmei,
first of all thanks for taking care of my questions. Saddly I'm still having the same error sin it fails at line 48 then tries to cast variable to float

Traceback (most recent call last):
  File "/MF/MuTect2-PoN_filter.py", line 48, in <module>
    AF=float(INFOs[2])
ValueError: could not convert string to float: '0.429,0.286'

this is a line previous to the last change you have made.

on the other hand, I was researching snakemake but I got a problem, I already have a PON database generated by GATK and I'm not able to get the source files (.BAM) to create that pon from scratch. Do you know if I can bypass the PON creation and use one that I already have?

PS: I'm using this panel of normals: gs://gatk-best-practices/somatic-hg38/1000g_pon.hg38.vcf.gz

Thanks
Valeria

**Comment by douym** [comment]
> Hello Yanmei,
> first of all thanks for taking care of my questions. Saddly I'm still having the same error since it fails at line 48 when it tries to cast variable to float. (what I belive)
> 
> Traceback (most recent call last):
> File "/MF/MuTect2-PoN_filter.py", line 48, in
> AF=float(INFOs[2])
> ValueError: could not convert string to float: '0.429,0.286'
> 
> this is a line previous to the last change you have made.
> 
> on the other hand, I was researching snakemake but I got a problem, I already have a PON database generated by GATK and I'm not able to get the source files (.BAM) to create that PON from scratch. Do you know if I can bypass the PON creation and use one that I already have?
> 
> PS: I'm using this panel of normals: gs://gatk-best-practices/somatic-hg38/1000g_pon.hg38.vcf.gz
> 
> Thanks
> Valeria

Hi @vinayakvsv ,

Sure you can!

If you already have the vcf file of PON, then you don't need to run the first several steps in the Snakefile related with PON generation, such as "scatter_MT2_PON", "generate_args", and "combine_PONs". You could simply comment these steps out and do not run them.

Your panel of normals file "gs://gatk-best-practices/somatic-hg38/1000g_pon.hg38.vcf.gz" is equal to "pon2/PON_{num}_pon.vcf.gz" in the Snakemake file. Making a directory "pon2", rename the "gs://gatk-best-practices/somatic-hg38/1000g_pon.hg38.vcf.gz" and put it under the "pon2" directory would work. However, if you want to parallel your Mutect2 running on different chromosomes, then first you would need to do is to split your pon.gz to different chromosomes (please refer to here: https://www.biostars.org/p/173073/).

Similar for other steps in the Snakemake.

THanks,

Yanmei

**Comment by vmscmams** [comment]
Hello Yanmei,
Sorry for that many questions and thanks again for your time. 

I've change the Snakefile and use Snakemake to run the commands successfully but I got a hard stop at {sample}.MAF0.bed file. The error message is:

rule Phase:
    input: MF_CONDA/887.MAF0.bed, /media/thirdHDD/Dockershare/CONDA/Snakemake/hg38.fa, /media/thirdHDD/Dockershare/CONDA/Snakemake/k24.umap.wg.bw
    output: MF_Phase/887.phase

check the format of your input file:
chr	pos-1	pos	ref	alt	sample
check the format of your input file:
chr	pos-1	pos	ref	alt	sample
check the format of your input file:
chr	pos-1	pos	ref	alt	sample


This is the content of my {sample}.MAF0.bed file: 

chr14_GL000225v1_random	90018	90019	A	G	887
chr7	151016680	151016681	T	A	887
chr8	129751862	129751863	T	A	887
chr14	53950479	53950480	T	G	887


I've compared this content with several files in different forums and looks like the format is actually correct.

These are the steps I tried and it still fails:
-I deleted the first column named "chr" and left onyl the Crhomosome number.
-I run the command outside the Snakemake: "python Phase.py BAMs demo/Phasing Ref/GRCh38.fna   VCF/887.MAF0.bed 20 Map_score/hg38/k24.umap.wg.bw 2 bam"
-I double check the {sample}.bam and {sample}.bam.bai files and they are correct.

Finally your recommandation to use Snakemake to elimitate the Multi-allels was correct and I successfully move forward but in the Phasing step is where I got this new error.

¿do know if I'm missing something?

Thank you very very much!

**Comment by douym** [comment]
> Hello Yanmei,
> Sorry for that many questions and thanks again for your time.
> 
> I've change the Snakefile and use Snakemake to run the commands successfully but I got a hard stop at {sample}.MAF0.bed file. The error message is:
> 
> rule Phase:
> input: MF_CONDA/887.MAF0.bed, /media/thirdHDD/Dockershare/CONDA/Snakemake/hg38.fa, /media/thirdHDD/Dockershare/CONDA/Snakemake/k24.umap.wg.bw
> output: MF_Phase/887.phase
> 
> check the format of your input file:
> chr pos-1 pos ref alt sample
> check the format of your input file:
> chr pos-1 pos ref alt sample
> check the format of your input file:
> chr pos-1 pos ref alt sample
> 
> This is the content of my {sample}.MAF0.bed file:
> 
> chr14_GL000225v1_random 90018 90019 A G 887
> chr7 151016680 151016681 T A 887
> chr8 129751862 129751863 T A 887
> chr14 53950479 53950480 T G 887
> 
> I've compared this content with several files in different forums and looks like the format is actually correct.
> 
> These are the steps I tried and it still fails:
> -I deleted the first column named "chr" and left onyl the Crhomosome number.
> -I run the command outside the Snakemake: "python Phase.py BAMs demo/Phasing Ref/GRCh38.fna VCF/887.MAF0.bed 20 Map_score/hg38/k24.umap.wg.bw 2 bam"
> -I double check the {sample}.bam and {sample}.bam.bai files and they are correct.
> 
> Finally your recommandation to use Snakemake to elimitate the Multi-allels was correct and I successfully move forward but in the Phasing step is where I got this new error.
> 
> ¿do know if I'm missing something?
> 
> Thank you very very much!

Hi @vmscmams ,

Very sorry that you are confronted with so many errors... 

If you could run the command properly outside Snakemake, in theory you should also be able to run it within Snakemake. Could you check the Snakefile and see if the rule Phase is using the same command as you use outside Snakemake? 

Thanks a lot, and best wishes,
Yanmei

**Comment by vmscmams** [comment]
Hello Yanmei, 

Thank you very very much!

I was able to finish the analysis and resolve all my errors. I just wanted to ask you, what is the unrefined RF loaded model that I could use? I tried some but I still get 4 genotypes at the end of the prediction.

**Comment by douym** [comment]
> Hello Yanmei,
> 
> Thank you very very much!
> 
> I was able to finish the analysis and resolve all my errors. I just wanted to ask you, what is the unrefined RF loaded model that I could use? I tried some but I still get 4 genotypes at the end of the prediction.

Hi @vmscmams ,

Sorry for the delayed reply. I personally think there's no need to use the Phase model because the refined model performs much better than the Phase model (especially in the repeatmasker regions). You could use "brain_MT2-PON.250x_MosaicForecast-Phase_pvalue.rds" under "https://github.com/parklab/MosaicForecast/tree/master/models_trained" if you want to try using the phase model~

Thanks, and best wishes,

Yanmei
